// GENERATED by scripts/build-engine-bundle.mjs — do not edit. Source: src/lib/siteOps/engine/

// src/lib/siteOps/engine/library.ts
var SZ = { kind: "same_zone" };
var SF = { kind: "same_floor" };
var BW = { kind: "building_wide" };
var EX = { kind: "external" };
var CF = (delta) => ({ kind: "cross_floor", delta });
var TASK_TYPES = [
  // ════════ FOUNDATION / GROUNDWORK (substructure) — building singletons, the FIRST stage ════════
  // The master-dependency chain: clear → dig → footings → plinth → mass concrete. All building-wide
  // singletons (one per building), run strictly in order BEFORE any superstructure. The whole frame
  // (GF columns onward) hangs off `foundation`, the final pour, via the columns→foundation edge (R6).
  {
    id: "ground_clearance",
    label: "Ground clearance",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: []
    // the master start — site work precedes it (out of scope)
  },
  {
    id: "excavation",
    label: "Excavation",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: [{ pred: "ground_clearance", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "clear the site before digging" }]
  },
  {
    id: "pcc_bed",
    label: "PCC bed (footing base)",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: [{ pred: "excavation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "lean-concrete bed in the dug pit" }]
  },
  {
    id: "footing",
    label: "Footings",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: [{ pred: "pcc_bed", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "footing cast on the PCC bed" }]
  },
  {
    id: "footing_column",
    label: "Footing columns (to plinth)",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: [{ pred: "footing", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "starter columns rise from the footings to plinth" }]
  },
  {
    id: "backfill",
    label: "Backfilling & compaction",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: [{ pred: "footing_column", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "backfill around the footings and compact" }]
  },
  {
    id: "plinth_beam",
    label: "Plinth beams",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: [{ pred: "backfill", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "plinth beams tie the columns at plinth level" }]
  },
  {
    id: "plinth_fill",
    label: "Plinth filling & compaction",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: [{ pred: "plinth_beam", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "fill and compact inside the plinth" }]
  },
  {
    id: "foundation",
    label: "Foundation",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: [],
    seq: [{ pred: "plinth_fill", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "mass-concrete / anti-termite bed \u2014 substructure complete" }]
  },
  {
    id: "columns",
    label: "Columns",
    trade: "civil",
    layer: "structure",
    instancing: "per_floor",
    appliesTo: [],
    seq: [
      // R6 Foundation → Columns(GF). Scope same-zone in sheet; foundation is a building singleton,
      // so this links every columns node to it. Harmless on upper floors (already gated via the
      // slab chain below) and truthful: all columns ultimately rest on the foundation.
      { pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: SZ, note: "GF anchors to foundation" },
      // R5 Slab(floor) → Columns(floor+1): my columns need the deck below to stand on.
      { pred: "slab", nature: "IMPOSSIBLE", reason: "structural", scope: CF(-1), note: "deck to stand on" }
    ]
  },
  {
    id: "beams",
    label: "Beams",
    trade: "civil",
    layer: "structure",
    instancing: "per_floor",
    appliesTo: [],
    seq: [
      { pred: "columns", nature: "IMPOSSIBLE", reason: "structural", scope: SF, note: "no beam without column" }
      // R3
    ]
  },
  {
    id: "slab",
    label: "Slab",
    trade: "civil",
    layer: "structure",
    instancing: "per_floor",
    appliesTo: [],
    seq: [
      { pred: "beams", nature: "IMPOSSIBLE", reason: "structural", scope: SF, note: "slab rests on beams" }
      // R4
    ],
    conceals: []
    // structural; concealment handled by finishes
  },
  {
    id: "shuttering_removal",
    label: "Shuttering removal (de-prop)",
    trade: "civil",
    layer: "structure",
    instancing: "per_floor",
    appliesTo: [],
    seq: [
      // R7 Slab → Shuttering-removal. Sheet nature = "CURING-WAIT": encoded DESTRUCTIVE +
      // reason curing_time (de-propping green concrete ruins the slab; it is a TIME gate).
      { pred: "slab", nature: "DESTRUCTIVE", reason: "curing_time", scope: SF, note: "cure before de-prop (~time, not a trade)" }
    ]
  },
  {
    id: "blockwork",
    label: "Blockwork (walls)",
    trade: "masonry",
    layer: "structure",
    instancing: "per_floor",
    appliesTo: [],
    isGateway: true,
    // once a floor's walls are up, the whole services freedom-set fans out
    seq: [
      { pred: "slab", nature: "IMPOSSIBLE", reason: "structural", scope: SF, note: "walls need the deck" },
      // R9
      // R8 Shuttering-removal → Blockwork: "no work under a propped slab" (FLAG-1, FOUNDER-RULED).
      // A slab's props stand on the floor BELOW it, so while slab@(F+1) is propped/curing those
      // props occupy floor F — you cannot raise blockwork on floor F until the slab ABOVE is
      // de-propped. So blockwork@F is gated by shuttering_removal@(F+1): cross_floor delta +1.
      // Consequence (intended): the frame races UP, then blockwork follows floor-by-floor as props
      // come down — NOT interleaved per floor. The TOP occupied floor's blockwork is gated by the
      // terrace slab's de-prop, or by nothing if it is the topmost (the +1 edge simply drops).
      // It is NEVER gated by its OWN-floor deshutter.
      { pred: "shuttering_removal", nature: "DESTRUCTIVE", reason: "structural", scope: CF(1), note: "no work under a propped slab \u2014 the slab ABOVE must be de-propped" }
    ]
  },
  // ════════ SERVICES (muscle) — per_zone unless noted ════════
  {
    id: "conduit",
    label: "Electrical conduiting",
    trade: "electrical",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    freedomSet: "muscle_followers",
    hosts: ["wiring", "switchboard"],
    concealedBy: ["plaster"],
    seq: [
      { pred: "blockwork", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "conduit chased INTO brick" }
      // R10
    ]
  },
  {
    id: "in_wall_plumbing",
    label: "In-wall plumbing",
    trade: "plumbing",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["wet", "balcony", "common"],
    freedomSet: "muscle_followers",
    concealedBy: ["plaster"],
    // FOUNDER RED-PEN: the sheet carries both "In-wall plumbing" (R11/R15) and "Plumbing rough"
    // (R17/R31/R35). They overlap heavily in Indian practice (concealed pipe = rough-in). Encoded
    // as DISTINCT task-types per the sheet, not merged — flag for review, do not "improve".
    seq: [
      { pred: "blockwork", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "pipe runs in brick" }
      // R11
    ]
  },
  {
    id: "plumb_rough",
    label: "Plumbing rough-in",
    trade: "plumbing",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["wet", "balcony"],
    hosts: ["sanitary"],
    cohesion: [
      { with: "pressure_test", nature: "STRONG_PREF", reason: "quality", note: "test meaningless detached from rough" }
      // R35
    ],
    // FOUNDER RED-PEN (engine-flagged gap): the sheet gave plumb_rough no predecessor, so it floated
    // to the very start of Services (before walls). Rough-in pipes are chased into the masonry / laid
    // against walls — like in-wall plumbing, it follows blockwork. Added:
    seq: [
      { pred: "blockwork", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "rough-in chased into / against the walls" }
    ]
  },
  {
    id: "pressure_test",
    label: "Pressure test",
    trade: "plumbing",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["wet", "balcony"],
    seq: [
      { pred: "plumb_rough", nature: "STRONG_PREF", reason: "quality", scope: SZ, note: "test before concealing \u2014 catch leaks" }
      // R17
    ]
  },
  {
    id: "wiring",
    label: "Wiring (wire pulling)",
    trade: "electrical",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    hostedBy: ["conduit"],
    seq: [
      { pred: "conduit", nature: "IMPOSSIBLE", reason: "logistics", scope: SZ, note: "wire needs conduit" }
      // R16
    ]
  },
  {
    id: "switchboard",
    label: "Switchboards / DB",
    trade: "electrical",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "common"],
    hostedBy: ["conduit"],
    seq: [
      { pred: "conduit", nature: "IMPOSSIBLE", reason: "logistics", scope: SZ, note: "board needs its wiring" }
      // R30
    ]
  },
  {
    id: "door_frame",
    label: "Door frames",
    trade: "carpentry",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    freedomSet: "muscle_followers",
    hosts: ["door_shutter"],
    seq: [
      // R12 promoted STRONG_PREF→IMPOSSIBLE (engine-flagged, FOUNDER-RULED): a door frame seats
      // INTO the masonry reveal — there is nothing to fix it to before the wall opening exists, so
      // it is impossible (not merely inadvisable) before blockwork. REVERT to STRONG_PREF only if
      // your sites set frames first with fixing lugs and build masonry around them.
      { pred: "blockwork", nature: "IMPOSSIBLE", reason: "logistics", scope: SZ, note: "frame seats into the masonry opening \u2014 needs the wall" },
      { pred: "conduit", nature: "WEAK_PREF", reason: "logistics", scope: SZ, note: "either order works" }
      // R19 (conduit→frames)
    ]
  },
  {
    id: "window_frame",
    label: "Window frames",
    trade: "carpentry",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    freedomSet: "muscle_followers",
    seq: [
      // R13 promoted STRONG_PREF→IMPOSSIBLE for the same reason as door frames: the jamb seats into
      // the masonry opening and cannot precede the wall. Applied for consistency with door_frame;
      // REVERT to STRONG_PREF if windows are set first with lugs. (engine-flagged, FOUNDER-RULED)
      { pred: "blockwork", nature: "IMPOSSIBLE", reason: "logistics", scope: SZ, note: "jamb seats into the masonry opening \u2014 needs the wall" },
      { pred: "conduit", nature: "WEAK_PREF", reason: "logistics", scope: SZ, note: "either order works" }
      // R19
    ]
  },
  {
    id: "ceiling_frame",
    label: "False-ceiling frame",
    trade: "ceiling",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["dry", "common"],
    hosts: ["overhead_service"],
    // FOUNDER RED-PEN (engine-flagged gap): the sheet authored NO predecessor, so the engine
    // honestly reported "available before walls exist". A false ceiling hangs from the slab soffit
    // and its perimeter channel anchors to the walls — it cannot exist before the floor's
    // structure, and not meaningfully before blockwork. Two edges added:
    seq: [
      { pred: "slab", nature: "IMPOSSIBLE", reason: "structural", scope: SZ, note: "false ceiling hangs from the slab soffit" },
      { pred: "blockwork", nature: "DESTRUCTIVE", reason: "logistics", scope: SZ, note: "perimeter channel anchors to the walls \u2014 framing before walls means redoing the perimeter" }
    ]
  },
  {
    id: "overhead_service",
    label: "Overhead services (in ceiling void)",
    trade: "mep",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["dry", "common"],
    freedomSet: "overhead_void",
    hostedBy: ["ceiling_frame"],
    concealedBy: ["ceiling_board"],
    seq: [
      { pred: "ceiling_frame", nature: "STRONG_PREF", reason: "logistics", scope: SZ, note: "service hung on frame" }
      // R27
    ]
  },
  {
    id: "void_wiring",
    label: "Ceiling void-wiring",
    trade: "electrical",
    layer: "services",
    instancing: "per_zone",
    appliesTo: ["dry", "common"],
    freedomSet: "overhead_void",
    concealedBy: ["pop_finish"],
    cohesion: [
      { with: "pop_finish", nature: "DESTRUCTIVE", reason: "concealment", note: "POP conceals wiring \u2192 move together" }
      // R34
    ],
    // FOUNDER RED-PEN (engine-flagged gap): authored with no predecessor, so it floated to the top of
    // Services. Wiring run in the ceiling void belongs with the overhead_void set, after the frame
    // that forms the void. Added as a soft order anchor (it can be partly pre-run, so not hard):
    seq: [
      { pred: "ceiling_frame", nature: "STRONG_PREF", reason: "logistics", scope: SZ, note: "run in the ceiling void the frame forms" }
    ]
  },
  // ════════ FINISHES (skin) — per_zone unless noted ════════
  {
    id: "plaster",
    label: "Plastering",
    trade: "plaster",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    conceals: ["conduit", "in_wall_plumbing", "pressure_test"],
    hosts: ["switchplate"],
    seq: [
      { pred: "conduit", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "plaster hides conduit; un-cover to fix" },
      // R14
      { pred: "in_wall_plumbing", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "pipe concealed by plaster" },
      // R15
      // R18 Pressure-test → Conceal(floor): the sheet's generic "Conceal" is realized here as
      // plaster (the concealing finish over in-wall lines). §8 domain rule: never bury an
      // untested pipe. Where pressure_test exists in a zone, it precedes that zone's plaster.
      { pred: "pressure_test", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "never conceal an untested line (R18)" }
    ]
  },
  {
    id: "waterproof",
    label: "Waterproofing",
    trade: "waterproofing",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["wet", "balcony"],
    concealedBy: ["screed", "floor_tile"],
    cohesion: [
      { with: "screed", nature: "DESTRUCTIVE", reason: "concealment", note: "stacked covers move as one" }
      // R36
    ],
    seq: []
  },
  {
    id: "screed",
    label: "Screed / leveling",
    trade: "flooring",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    conceals: ["waterproof"],
    concealedBy: ["floor_tile"],
    seq: [
      { pred: "waterproof", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "screed covers WP" }
      // R20
    ]
  },
  {
    id: "floor_tile",
    label: "Floor tiling",
    trade: "tiling",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    conceals: ["screed", "waterproof"],
    seq: [
      { pred: "screed", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "tile over screed" },
      // R21
      { pred: "waterproof", nature: "DESTRUCTIVE", reason: "quality", scope: SZ, note: "WP must underlie wet floor" }
      // R22
    ]
  },
  {
    id: "wall_tile",
    label: "Wall tiling / dado",
    trade: "tiling",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["wet"],
    seq: [
      { pred: "plaster", nature: "STRONG_PREF", reason: "quality", scope: SZ, note: "tile backing" }
      // R24
    ]
  },
  {
    id: "paint",
    label: "Painting",
    trade: "painting",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    freedomSet: "room_finishing",
    seq: [
      { pred: "plaster", nature: "DESTRUCTIVE", reason: "quality", scope: SZ, note: "paint needs plastered surface" },
      // R23
      { pred: "floor_tile", nature: "WEAK_PREF", reason: "quality", scope: SZ, note: "or paint-then-floor; protect either way" }
      // R26
    ]
  },
  {
    id: "switchplate",
    label: "Switchplates / faceplates",
    trade: "electrical",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "common"],
    freedomSet: "skin_fittings",
    hostedBy: ["plaster"],
    seq: [
      { pred: "plaster", nature: "STRONG_PREF", reason: "logistics", scope: SZ, note: "mount on finished wall" }
      // R25
    ]
  },
  {
    id: "ceiling_board",
    label: "Ceiling boarding",
    trade: "ceiling",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["dry", "common"],
    conceals: ["overhead_service"],
    seq: [
      { pred: "overhead_service", nature: "DESTRUCTIVE", reason: "concealment", scope: SZ, note: "board seals the void" }
      // R28
    ]
  },
  {
    id: "pop_finish",
    label: "POP / ceiling finish",
    trade: "ceiling",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["dry", "common"],
    conceals: ["void_wiring"],
    seq: [
      { pred: "ceiling_board", nature: "STRONG_PREF", reason: "quality", scope: SZ, note: "finish over board" }
      // R29
    ]
  },
  {
    id: "sanitary",
    label: "Sanitaryware / fittings",
    trade: "plumbing",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["wet"],
    freedomSet: "skin_fittings",
    hostedBy: ["plumb_rough"],
    seq: [
      { pred: "plumb_rough", nature: "IMPOSSIBLE", reason: "logistics", scope: SZ, note: "fittings need rough-in" },
      // R31
      { pred: "wall_tile", nature: "STRONG_PREF", reason: "quality", scope: SZ, note: "fittings on tiled wall" }
      // R33
    ]
  },
  {
    id: "door_shutter",
    label: "Door shutters",
    trade: "carpentry",
    layer: "finishes",
    instancing: "per_zone",
    appliesTo: ["dry", "wet", "balcony", "common"],
    freedomSet: "skin_fittings",
    hostedBy: ["door_frame"],
    seq: [
      { pred: "door_frame", nature: "IMPOSSIBLE", reason: "logistics", scope: SZ, note: "shutter hangs on frame" }
      // R32
    ]
  },
  // ════════ COMMON / EXTERNAL / LONG-LEAD — building / external ════════
  {
    id: "external_structure",
    label: "External / fa\xE7ade structure",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: ["external"],
    seq: []
  },
  {
    id: "facade_plaster",
    label: "Fa\xE7ade plaster",
    trade: "plaster",
    layer: "finishes",
    instancing: "building",
    appliesTo: ["external"],
    freedomSet: "common_stream",
    seq: [
      { pred: "external_structure", nature: "STRONG_PREF", reason: "logistics", scope: BW, note: "scaffolding / access" }
      // R37
    ]
  },
  {
    id: "lift_shaft",
    label: "Lift-shaft structure",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: ["shaft"],
    seq: []
  },
  {
    id: "lift_mechanism",
    label: "Lift mechanism",
    trade: "lift",
    layer: "services",
    instancing: "building",
    appliesTo: ["shaft"],
    longLead: true,
    // start procurement early though install is late
    seq: [
      { pred: "lift_shaft", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "LONG-LEAD: start early" }
      // R38
    ]
  },
  {
    id: "site_grade",
    label: "Site grading",
    trade: "civil",
    layer: "structure",
    instancing: "building",
    appliesTo: ["external"],
    seq: []
  },
  {
    id: "site_development",
    label: "Site development",
    trade: "civil",
    layer: "finishes",
    instancing: "building",
    appliesTo: ["external"],
    freedomSet: "common_stream",
    seq: [
      { pred: "site_grade", nature: "STRONG_PREF", reason: "logistics", scope: EX, note: "near handover" }
      // R39
    ]
  },
  // ════════ COMMON AREAS / AMENITIES — building singletons, OPT-IN per project ════════
  // Each is gated by the project's enabled common-systems set (instantiate.buildingTypeEnabled): a
  // `ca_*` node only instantiates when the project ticked it. All sit on the substructure (after
  // `foundation`), run parallel to each other and to the unit work, and surface as one "Common areas"
  // stage in the timeline. Anchors are deliberately light — these are managed as a parallel stream.
  { id: "ca_parking", label: "Parking deck & markings", trade: "civil", layer: "structure", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "built on the substructure" }] },
  { id: "ca_stair", label: "Common staircase", trade: "civil", layer: "structure", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "rises from the substructure" }] },
  { id: "ca_ugt", label: "Underground sump / tank", trade: "civil", layer: "structure", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "cast with the substructure" }] },
  { id: "ca_stp", label: "Sewage treatment plant (STP)", trade: "civil", layer: "structure", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "below-grade plant" }] },
  { id: "ca_compound", label: "Compound wall & gate", trade: "civil", layer: "structure", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "site boundary" }] },
  { id: "ca_lift", label: "Lift (shaft & cabin)", trade: "lift", layer: "services", instancing: "building", appliesTo: [], longLead: true, seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "LONG-LEAD: order early" }] },
  { id: "ca_transformer", label: "Transformer / substation", trade: "electrical", layer: "services", instancing: "building", appliesTo: [], longLead: true, seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "LONG-LEAD power infra" }] },
  { id: "ca_generator", label: "DG / generator set", trade: "electrical", layer: "services", instancing: "building", appliesTo: [], longLead: true, seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "backup power" }] },
  { id: "ca_oht", label: "Overhead tank & pumps", trade: "plumbing", layer: "services", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "water storage & pumping" }] },
  { id: "ca_fire", label: "Fire fighting (pumps, sprinklers, alarm)", trade: "fire", layer: "services", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "building-wide fire system" }] },
  { id: "ca_solar", label: "Rooftop solar", trade: "electrical", layer: "services", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "roof-mounted PV" }] },
  { id: "ca_borewell", label: "Borewell", trade: "plumbing", layer: "services", instancing: "building", appliesTo: [], seq: [{ pred: "foundation", nature: "IMPOSSIBLE", reason: "structural", scope: BW, note: "water source" }] },
  { id: "ca_corridor", label: "Corridor & lobby finishes", trade: "finishing", layer: "finishes", instancing: "building", appliesTo: [], seq: [{ pred: "ca_stair", nature: "STRONG_PREF", reason: "logistics", scope: BW, note: "finish after the common structure" }] },
  { id: "ca_landscaping", label: "Landscaping & hardscape", trade: "landscaping", layer: "finishes", instancing: "building", appliesTo: [], seq: [{ pred: "ca_compound", nature: "STRONG_PREF", reason: "logistics", scope: BW, note: "near handover, inside the boundary" }] }
];
var FREEDOM_SETS = [
  {
    id: "muscle_followers",
    label: "Muscle followers of brick",
    members: ["conduit", "in_wall_plumbing", "door_frame", "window_frame"],
    // sheet also lists ELV (no task-type yet)
    earliestAfter: "blockwork",
    latestBefore: "plaster",
    scope: "per_zone",
    note: "after blockwork \u2192 before plaster"
  },
  {
    id: "room_finishing",
    label: "Room finishing order",
    members: ["paint"],
    // room-by-room paint; per-floor freedom (each after its own plaster)
    earliestAfter: "plaster",
    latestBefore: null,
    scope: "per_floor",
    note: "each after its own plaster \u2192 before handover"
  },
  {
    id: "skin_fittings",
    label: "Skin-phase fittings",
    members: ["switchplate", "sanitary", "door_shutter"],
    // sheet also lists light fixtures (no task-type yet)
    earliestAfter: null,
    latestBefore: null,
    scope: "per_zone",
    note: "after own-muscle + surface \u2192 before handover"
  },
  {
    id: "overhead_void",
    label: "Overhead services in ceiling void",
    members: ["overhead_service", "void_wiring"],
    earliestAfter: "ceiling_frame",
    latestBefore: "ceiling_board",
    scope: "per_zone",
    note: "after ceiling frame \u2192 before board"
  },
  {
    id: "common_stream",
    label: "Common-area stream vs unit work",
    members: ["facade_plaster", "site_development"],
    earliestAfter: null,
    latestBefore: null,
    scope: "building_wide",
    note: "run parallel to units; after own structure \u2192 near handover"
  }
];
var CANONICAL_SEQUENCE = [
  // foundation / groundwork (substructure) — the first stage, building singletons
  "ground_clearance",
  "excavation",
  "pcc_bed",
  "footing",
  "footing_column",
  "backfill",
  "plinth_beam",
  "plinth_fill",
  "foundation",
  // structure (bones)
  "columns",
  "beams",
  "slab",
  "shuttering_removal",
  "blockwork",
  // services (muscle) — wall services, then ceiling-void services
  "conduit",
  "in_wall_plumbing",
  "plumb_rough",
  "pressure_test",
  "door_frame",
  "window_frame",
  "wiring",
  "switchboard",
  "ceiling_frame",
  "overhead_service",
  "void_wiring",
  // finishes (skin) — plaster → wet-floor stack → tiling → ceiling finish → paint → fittings
  "plaster",
  "waterproof",
  "screed",
  "floor_tile",
  "wall_tile",
  "ceiling_board",
  "pop_finish",
  "paint",
  "switchplate",
  "sanitary",
  "door_shutter",
  // common / external / long-lead
  "external_structure",
  "facade_plaster",
  "lift_shaft",
  "lift_mechanism",
  "site_grade",
  "site_development",
  // common areas / amenities (opt-in per project)
  "ca_parking",
  "ca_stair",
  "ca_ugt",
  "ca_stp",
  "ca_compound",
  "ca_lift",
  "ca_transformer",
  "ca_generator",
  "ca_oht",
  "ca_fire",
  "ca_solar",
  "ca_borewell",
  "ca_corridor",
  "ca_landscaping"
];
function canonicalRank(lib = LIBRARY) {
  const m = /* @__PURE__ */ new Map();
  CANONICAL_SEQUENCE.forEach((id, i) => {
    if (lib.taskTypes.has(id)) m.set(id, i);
  });
  return m;
}
function buildLibrary() {
  const taskTypes = new Map(TASK_TYPES.map((t) => [t.id, t]));
  const freedomSets = new Map(FREEDOM_SETS.map((f) => [f.id, f]));
  return { taskTypes, freedomSets };
}
var LIBRARY = buildLibrary();
function validateLibrary(lib = LIBRARY) {
  const issues = [];
  const ids = lib.taskTypes;
  for (const t of ids.values()) {
    for (const e of t.seq)
      if (!ids.has(e.pred)) issues.push({ kind: "unknown_pred", detail: `${t.id}.seq \u2192 unknown '${e.pred}'` });
    for (const c of t.cohesion ?? [])
      if (!ids.has(c.with)) issues.push({ kind: "unknown_cohesion", detail: `${t.id}.cohesion \u2192 unknown '${c.with}'` });
    for (const field of ["conceals", "concealedBy", "hosts", "hostedBy"])
      for (const ref of t[field] ?? [])
        if (!ids.has(ref)) issues.push({ kind: "unknown_semantic", detail: `${t.id}.${field} \u2192 unknown '${ref}'` });
    if (t.freedomSet && !lib.freedomSets.has(t.freedomSet))
      issues.push({ kind: "unknown_freedom_set", detail: `${t.id}.freedomSet \u2192 unknown '${t.freedomSet}'` });
  }
  for (const f of lib.freedomSets.values()) {
    for (const m of f.members)
      if (!ids.has(m)) issues.push({ kind: "unknown_member", detail: `freedomSet ${f.id} \u2192 unknown member '${m}'` });
    for (const a of [f.earliestAfter, f.latestBefore])
      if (a && !ids.has(a)) issues.push({ kind: "unknown_anchor", detail: `freedomSet ${f.id} \u2192 unknown anchor '${a}'` });
  }
  const cycle = findAbstractCycle(lib);
  if (cycle) issues.push({ kind: "cycle", detail: `authored cycle: ${cycle.join(" \u2192 ")}` });
  const rank = canonicalRank(lib);
  for (const id of ids.keys())
    if (!rank.has(id)) issues.push({ kind: "canon_missing", detail: `task-type '${id}' not in CANONICAL_SEQUENCE` });
  const seen = /* @__PURE__ */ new Set();
  for (const id of CANONICAL_SEQUENCE) {
    if (seen.has(id)) issues.push({ kind: "canon_dup", detail: `'${id}' listed twice in CANONICAL_SEQUENCE` });
    seen.add(id);
  }
  for (const t of ids.values())
    for (const e of t.seq) {
      const crossFloor = e.scope.kind === "cross_floor" && e.scope.delta !== 0;
      if (!isHardNature(e.nature, e.reason) || crossFloor) continue;
      const rp = rank.get(e.pred), rf = rank.get(t.id);
      if (rp !== void 0 && rf !== void 0 && rp >= rf)
        issues.push({ kind: "canon_violates_hard", detail: `CANONICAL_SEQUENCE puts '${e.pred}' at/after its hard follower '${t.id}'` });
    }
  return issues;
}
function isHardNature(nature, reason) {
  return nature === "IMPOSSIBLE" || nature === "DESTRUCTIVE" || reason === "curing_time";
}
function findAbstractCycle(lib) {
  const WHITE = 0, GRAY = 1, BLACK = 2;
  const color = /* @__PURE__ */ new Map();
  const stack = [];
  const adj = /* @__PURE__ */ new Map();
  for (const t of lib.taskTypes.values())
    for (const e of t.seq) {
      const crossFloor = e.scope.kind === "cross_floor" && e.scope.delta !== 0;
      if (isHardNature(e.nature, e.reason) && !crossFloor) {
        if (!adj.has(e.pred)) adj.set(e.pred, []);
        adj.get(e.pred).push(t.id);
      }
    }
  let found = null;
  const visit = (n) => {
    if (found) return;
    color.set(n, GRAY);
    stack.push(n);
    for (const m of adj.get(n) ?? []) {
      if (found) break;
      const c = color.get(m) ?? WHITE;
      if (c === GRAY) {
        found = [...stack.slice(stack.indexOf(m)), m];
        break;
      }
      if (c === WHITE) visit(m);
    }
    stack.pop();
    color.set(n, BLACK);
  };
  for (const t of lib.taskTypes.values()) if ((color.get(t.id) ?? WHITE) === WHITE) visit(t.id);
  return found;
}
function taskType(id, lib = LIBRARY) {
  const t = lib.taskTypes.get(id);
  if (!t) throw new Error(`unknown task-type '${id}'`);
  return t;
}

// src/lib/siteOps/engine/instantiate.ts
function buildingNodeId(tid) {
  return tid;
}
function perFloorNodeId(tid, floorLabel) {
  return `${tid}@${floorLabel}`;
}
function perZoneNodeId(tid, floorLabel, zoneId) {
  return `${tid}@${floorLabel}#${zoneId}`;
}
var LAYER_ORDER = { structure: 0, services: 1, finishes: 2 };
var HABITABLE_ZONE_KINDS = ["dry", "wet", "balcony"];
function stackToGeometry(stack, opts = {}) {
  const floors = stack.levels.map((level, index) => {
    const zones = [];
    if (level.kind === "parking") {
      zones.push({ id: `${level.label}-parking`, kind: "common", floorLabel: level.label, unitLabel: null });
    } else {
      for (const z of level.zones.filter((zz) => zz.use !== "parking")) {
        const units = Math.max(1, z.units);
        for (let u = 0; u < units; u++) {
          const unitLabel = units === 1 ? null : `Unit ${String.fromCharCode(65 + u)}`;
          const tag = unitLabel ? unitLabel.replace(/\s+/g, "") : "unit";
          for (const kind of HABITABLE_ZONE_KINDS)
            zones.push({ id: `${level.label}-${tag}-${kind}`, kind, floorLabel: level.label, unitLabel });
        }
      }
    }
    return { label: level.label, index, zones };
  });
  return {
    floors,
    hasLift: opts.hasLift ?? false,
    hasCommonAreas: opts.hasCommonAreas ?? false,
    hasExternalWorks: opts.hasExternalWorks ?? false,
    commonSystems: new Set(opts.commonSystems ?? []),
    suppressedTasks: new Set(opts.suppressedTasks ?? [])
  };
}
var CycleError = class extends Error {
  cycleEdges;
  constructor(cycleEdges) {
    super(`hard cycle in concrete graph (${cycleEdges.length} edge(s)): ` + cycleEdges.map((e) => `${e.from} \u2192 ${e.to}`).join(", "));
    this.name = "CycleError";
    this.cycleEdges = cycleEdges;
  }
};
function makeNode(t, floor, zone) {
  const id = !floor ? buildingNodeId(t.id) : !zone ? perFloorNodeId(t.id, floor.label) : perZoneNodeId(t.id, floor.label, zone.id);
  return {
    id,
    taskTypeId: t.id,
    label: t.label,
    trade: t.trade,
    layer: t.layer,
    floorLabel: floor?.label ?? null,
    floorIndex: floor?.index ?? null,
    unitLabel: zone?.unitLabel ?? null,
    zoneId: zone?.id ?? null,
    zoneKind: zone?.kind ?? null,
    seqNo: 0,
    placementSource: "authored",
    source: "generated"
  };
}
function buildingTypeEnabled(t, geo) {
  if (t.id.startsWith("ca_")) return geo.commonSystems?.has(t.id) ?? false;
  if (t.id === "lift_shaft" || t.id === "lift_mechanism") return !!geo.hasLift;
  if (t.id === "facade_plaster" || t.id === "external_structure") return geo.hasExternalWorks ?? true;
  if (t.id === "site_grade" || t.id === "site_development") return geo.hasExternalWorks ?? true;
  return true;
}
function instantiate(geometry, lib = LIBRARY, extraTaskTypes = []) {
  const types = new Map(lib.taskTypes);
  for (const x of extraTaskTypes) types.set(x.id, x);
  const nodes = /* @__PURE__ */ new Map();
  const floorByIndex = /* @__PURE__ */ new Map();
  for (const f of geometry.floors) floorByIndex.set(f.index, f);
  for (const t of types.values()) {
    if (geometry.suppressedTasks?.has(t.id)) continue;
    if (t.instancing === "building") {
      if (buildingTypeEnabled(t, geometry)) {
        const n = makeNode(t, null, null);
        if (extraTaskTypes.some((x) => x.id === t.id)) n.placementSource = "classified";
        nodes.set(n.id, n);
      }
    } else if (t.instancing === "per_floor") {
      for (const f of geometry.floors) {
        const n = makeNode(t, f, null);
        if (extraTaskTypes.some((x) => x.id === t.id)) n.placementSource = "classified";
        nodes.set(n.id, n);
      }
    } else {
      for (const f of geometry.floors)
        for (const z of f.zones)
          if (t.appliesTo.includes(z.kind)) {
            const n = makeNode(t, f, z);
            if (extraTaskTypes.some((x) => x.id === t.id)) n.placementSource = "classified";
            nodes.set(n.id, n);
          }
    }
  }
  const edges = [];
  const addEdge = (from, to, nature, reason, note) => {
    if (from && nodes.has(from) && nodes.has(to) && from !== to) edges.push({ from, to, nature, reason, note });
  };
  for (const follower of nodes.values()) {
    const t = types.get(follower.taskTypeId);
    for (const e of t.seq) {
      const predIds = resolvePred(e.pred, e.scope, follower, types, floorByIndex, geometry);
      for (const pid of predIds) addEdge(pid, follower.id, e.nature, e.reason, e.note);
    }
  }
  const bundles = [];
  const seenBundle = /* @__PURE__ */ new Set();
  for (const node of nodes.values()) {
    const t = types.get(node.taskTypeId);
    for (const c of t.cohesion ?? []) {
      const partners = resolvePred(c.with, { kind: "same_zone" }, node, types, floorByIndex, geometry);
      for (const pid of partners) {
        const key = [node.id, pid].sort().join("|");
        if (seenBundle.has(key)) continue;
        seenBundle.add(key);
        bundles.push({ members: [node.id, pid], nature: c.nature, reason: c.reason });
      }
    }
  }
  const seqNoByNode = topoSort(nodes, edges);
  for (const [id, seq] of seqNoByNode) nodes.get(id).seqNo = seq;
  return { nodes, edges, bundles, seqNoByNode };
}
function resolvePred(predId, scope, follower, types, floorByIndex, geometry) {
  const pt = types.get(predId);
  if (!pt) return [];
  if (pt.instancing === "building") return [buildingNodeId(predId)];
  const fIdx = follower.floorIndex;
  const predFloorIndex = scope.kind === "cross_floor" ? (fIdx ?? 0) + scope.delta : fIdx ?? 0;
  if (pt.instancing === "per_floor") {
    if (fIdx === null) return [];
    const f = floorByIndex.get(predFloorIndex);
    return f ? [perFloorNodeId(predId, f.label)] : [];
  }
  if (scope.kind === "same_zone" || scope.kind === "cross_floor") {
    if (follower.zoneId) {
      const f2 = floorByIndex.get(predFloorIndex);
      if (!f2) return [];
      const z = f2.zones.find((zz) => zz.id === follower.zoneId);
      if (z && pt.appliesTo.includes(z.kind)) return [perZoneNodeId(predId, f2.label, z.id)];
      return [];
    }
    const f = floorByIndex.get(predFloorIndex);
    if (!f) return [];
    return f.zones.filter((z) => pt.appliesTo.includes(z.kind)).map((z) => perZoneNodeId(predId, f.label, z.id));
  }
  if (scope.kind === "same_floor") {
    const f = floorByIndex.get(predFloorIndex);
    if (!f) return [];
    return f.zones.filter((z) => pt.appliesTo.includes(z.kind)).map((z) => perZoneNodeId(predId, f.label, z.id));
  }
  const out = [];
  for (const f of geometry.floors)
    for (const z of f.zones)
      if (pt.appliesTo.includes(z.kind)) out.push(perZoneNodeId(predId, f.label, z.id));
  return out;
}
function topoSort(nodes, edges) {
  const hard = edges.filter((e) => isHardNature(e.nature, e.reason));
  const indeg = /* @__PURE__ */ new Map();
  const adj = /* @__PURE__ */ new Map();
  for (const id of nodes.keys()) {
    indeg.set(id, 0);
    adj.set(id, []);
  }
  for (const e of hard) {
    if (!nodes.has(e.from) || !nodes.has(e.to)) continue;
    adj.get(e.from).push(e.to);
    indeg.set(e.to, (indeg.get(e.to) ?? 0) + 1);
  }
  const cmp = (a, b) => {
    const na = nodes.get(a), nb = nodes.get(b);
    const fa = na.floorIndex ?? -1, fb = nb.floorIndex ?? -1;
    if (fa !== fb) return fa - fb;
    const la = LAYER_ORDER[na.layer] ?? 9, lb = LAYER_ORDER[nb.layer] ?? 9;
    if (la !== lb) return la - lb;
    return a < b ? -1 : a > b ? 1 : 0;
  };
  let ready = [...nodes.keys()].filter((id) => (indeg.get(id) ?? 0) === 0).sort(cmp);
  const order = [];
  while (ready.length) {
    const n = ready.shift();
    order.push(n);
    const newlyReady = [];
    for (const m of adj.get(n)) {
      const d = (indeg.get(m) ?? 0) - 1;
      indeg.set(m, d);
      if (d === 0) newlyReady.push(m);
    }
    if (newlyReady.length) ready = [...ready, ...newlyReady].sort(cmp);
  }
  if (order.length !== nodes.size) {
    const placed = new Set(order);
    const stuck = [...nodes.keys()].filter((id) => !placed.has(id));
    const stuckSet = new Set(stuck);
    const cycleEdges = hard.filter((e) => stuckSet.has(e.from) && stuckSet.has(e.to));
    throw new CycleError(cycleEdges);
  }
  const seqNoByNode = /* @__PURE__ */ new Map();
  order.forEach((id, i) => seqNoByNode.set(id, i + 1));
  return seqNoByNode;
}
function buildAdjacency(graph) {
  const preds = /* @__PURE__ */ new Map();
  const succs = /* @__PURE__ */ new Map();
  for (const id of graph.nodes.keys()) {
    preds.set(id, []);
    succs.set(id, []);
  }
  for (const e of graph.edges) {
    preds.get(e.to)?.push(e);
    succs.get(e.from)?.push(e);
  }
  return { preds, succs };
}
function emptyState() {
  return /* @__PURE__ */ new Map();
}

// src/lib/siteOps/engine/evaluate.ts
var NATURE_RANK = {
  IMPOSSIBLE: 4,
  DESTRUCTIVE: 3,
  STRONG_PREF: 2,
  WEAK_PREF: 1,
  INDIFFERENT: 0
};
var Evaluator = class {
  graph;
  state;
  lib;
  preds;
  succs;
  constructor(graph, state = /* @__PURE__ */ new Map(), lib = LIBRARY) {
    this.graph = graph;
    this.state = state;
    this.lib = lib;
    const adj = buildAdjacency(graph);
    this.preds = adj.preds;
    this.succs = adj.succs;
  }
  statusOf(node) {
    return this.state.get(node) ?? "not_started";
  }
  isDone(node) {
    return this.statusOf(node) === "done";
  }
  /** Incoming HARD edges (the ones that gate availability). */
  hardPreds(node) {
    return (this.preds.get(node) ?? []).filter((e) => isHardNature(e.nature, e.reason));
  }
  // ── status(node) → done | active | available | blocked ──────────────────────
  availability(node) {
    const s = this.statusOf(node);
    if (s === "done") return "done";
    if (s === "active") return "active";
    const blocked = this.hardPreds(node).some((e) => !this.isDone(e.from));
    return blocked ? "blocked" : "available";
  }
  // ── why(node) → binding predecessors, most severe first ─────────────────────
  why(node) {
    const binders = this.hardPreds(node).filter((e) => !this.isDone(e.from));
    return binders.map((e) => ({
      node: e.from,
      taskTypeId: this.graph.nodes.get(e.from).taskTypeId,
      nature: e.nature,
      reason: e.reason,
      note: e.note
    })).sort((a, b) => NATURE_RANK[b.nature] - NATURE_RANK[a.nature]);
  }
  /** A self-explaining one-liner for a blocked node ("after Conduiting — concealment"). */
  whyMessage(node) {
    const binders = this.why(node);
    if (!binders.length) return null;
    const top = binders[0];
    const label = this.lib.taskTypes.get(top.taskTypeId)?.label ?? top.taskTypeId;
    return `after ${label} \u2014 ${top.reason}`;
  }
  // ── freedom(node) → [hard-earliest, hard-latest] span; grows as state advances ─
  freedom(node) {
    const tt = this.graph.nodes.get(node).taskTypeId;
    const setId = this.lib.taskTypes.get(tt)?.freedomSet ?? null;
    const earliestAfterDone = this.hardPreds(node).every((e) => this.isDone(e.from));
    const latestBefore = (this.succs.get(node) ?? []).filter((e) => isHardNature(e.nature, e.reason)).map((e) => e.to);
    let fullyFree = false;
    if (setId) {
      const set = this.lib.freedomSets.get(setId);
      const anchorDone = !set?.earliestAfter ? true : this.anchorSatisfied(node, set.earliestAfter);
      fullyFree = earliestAfterDone && anchorDone;
    }
    return { fullyFree, earliestAfterDone, latestBefore, freedomSet: setId };
  }
  /** True if the freedom-set's earliest-anchor task is done in the node's locale. */
  anchorSatisfied(node, anchorType) {
    const anchorPred = (this.preds.get(node) ?? []).find(
      (e) => this.graph.nodes.get(e.from).taskTypeId === anchorType
    );
    return anchorPred ? this.isDone(anchorPred.from) : true;
  }
  // ── priority(availableSet, policy) → advisory order; never blocks a free choice ─
  priority(available, policy = "structure_first") {
    const layerRank = { structure: 0, services: 1, finishes: 2 };
    const score = (id) => {
      const n = this.graph.nodes.get(id);
      const softPending = (this.preds.get(id) ?? []).filter((e) => e.nature === "STRONG_PREF" && !this.isDone(e.from)).length;
      let policyKey = 0;
      const floor = n.floorIndex ?? 0;
      switch (policy) {
        case "structure_first":
          policyKey = layerRank[n.layer] ?? 9;
          break;
        case "floor_complete":
          policyKey = floor * 10 + (layerRank[n.layer] ?? 9);
          break;
        case "watertight_first":
          policyKey = n.zoneKind === "wet" || n.zoneKind === "external" ? 0 : 1;
          break;
        case "own_practice":
          policyKey = 0;
          break;
      }
      return [softPending, policyKey, floor, layerRank[n.layer] ?? 9, n.seqNo];
    };
    return [...available].sort((a, b) => {
      const sa = score(a), sb = score(b);
      for (let i = 0; i < sa.length; i++) if (sa[i] !== sb[i]) return sa[i] - sb[i];
      return a < b ? -1 : a > b ? 1 : 0;
    });
  }
  /** All nodes currently `available` (hard preds done, not yet active/done). */
  availableSet() {
    return [...this.graph.nodes.keys()].filter((id) => this.availability(id) === "available");
  }
  // ── cohesionSet(node) → the bundle that relocates with it ───────────────────
  cohesionSet(node) {
    const out = /* @__PURE__ */ new Set([node]);
    let grew = true;
    while (grew) {
      grew = false;
      for (const b of this.graph.bundles) {
        if (b.members.some((m) => out.has(m))) {
          for (const m of b.members) {
            if (this.isDone(m)) continue;
            if (!out.has(m)) {
              out.add(m);
              grew = true;
            }
          }
        }
      }
    }
    return [...out];
  }
  // ── checkMove(node, targetSeqNo) → the drag verdict ─────────────────────────
  // Verdict from the most severe predecessor that would end up AFTER the target position.
  // Unknown (a hard pred we can't resolve) → WARN, never silent allow.
  checkMove(node, targetSeqNo) {
    const bundle = this.cohesionSet(node);
    let worst = null;
    for (const e of this.preds.get(node) ?? []) {
      const predNode = this.graph.nodes.get(e.from);
      if (!predNode) {
        if (!worst || NATURE_RANK[e.nature] >= NATURE_RANK[worst.nature])
          worst = { nature: e.nature, reason: e.reason, note: e.note };
        continue;
      }
      if (predNode.seqNo >= targetSeqNo) {
        if (!worst || NATURE_RANK[e.nature] > NATURE_RANK[worst.nature])
          worst = { nature: e.nature, reason: e.reason, note: e.note };
      }
    }
    if (!worst) {
      const span = this.freedom(node);
      const msg = span.fullyFree ? "fully free \u2014 any order within its set" : "allowed";
      return { verdict: "allow", reason: null, nature: null, message: msg, movesBundle: bundle };
    }
    const verdict = verdictFor(worst.nature);
    return {
      verdict,
      reason: worst.reason,
      nature: worst.nature,
      message: messageFor(verdict, worst.reason, worst.note),
      movesBundle: bundle
    };
  }
};
function verdictFor(nature) {
  switch (nature) {
    case "IMPOSSIBLE":
      return "forbid";
    case "DESTRUCTIVE":
      return "allow_with_consequence";
    case "STRONG_PREF":
      return "warn";
    case "WEAK_PREF":
      return "suggest";
    case "INDIFFERENT":
      return "allow";
  }
}
function messageFor(verdict, reason, note) {
  switch (verdict) {
    case "forbid":
      return `Not possible \u2014 ${reason}: ${note}`;
    case "allow_with_consequence":
      return `Allowed but destructive \u2014 ${reason}: ${note}`;
    case "warn":
      return `Not recommended \u2014 ${reason}: ${note}`;
    case "suggest":
      return `Mild preference \u2014 ${reason}: ${note}`;
    case "allow":
      return "allowed";
  }
}
function evaluate(graph, state = /* @__PURE__ */ new Map(), lib = LIBRARY) {
  return new Evaluator(graph, state, lib);
}
function stateOf(opts = {}) {
  const m = /* @__PURE__ */ new Map();
  for (const id of opts.done ?? []) m.set(id, "done");
  for (const id of opts.active ?? []) m.set(id, "active");
  return m;
}

// src/lib/siteOps/engine/classify.ts
var NATURES = /* @__PURE__ */ new Set(["IMPOSSIBLE", "DESTRUCTIVE", "STRONG_PREF", "WEAK_PREF", "INDIFFERENT"]);
var REASONS = /* @__PURE__ */ new Set(["structural", "concealment", "curing_time", "logistics", "quality", "policy"]);
var LAYERS = /* @__PURE__ */ new Set(["structure", "services", "finishes"]);
var ZONE_KINDS = /* @__PURE__ */ new Set(["dry", "wet", "balcony", "common", "external", "shaft"]);
var SCOPE_KINDS = /* @__PURE__ */ new Set(["same_zone", "same_floor", "cross_floor", "building_wide", "external"]);
var SAFE_NATURE = "STRONG_PREF";
var SAFE_REASON = "logistics";
var SAFE_SCOPE = { kind: "same_zone" };
function buildClassifierPrompt(ctx, lib = LIBRARY) {
  const vocab = [...lib.taskTypes.values()].map(
    (t) => `  ${t.id} \u2014 ${t.label} [${t.layer}]` + (t.conceals?.length ? ` conceals:${t.conceals.join(",")}` : "") + (t.hosts?.length ? ` hosts:${t.hosts.join(",")}` : "")
  ).join("\n");
  const sets = [...lib.freedomSets.values()].map((f) => `  ${f.id} \u2014 ${f.label} (${f.note})`).join("\n");
  const local = (ctx.localTasks ?? []).map((t) => `  ${t.taskTypeId}:${t.status}`).join("\n") || "  (none)";
  return [
    "You map a user-added construction task onto an EXISTING constraint library. You DO NOT invent",
    'new physics. Every placement edge MUST reference an existing TaskTypeId below (or "UNKNOWN").',
    "Return STRICT JSON matching ClassifierLLMOutput. Choose anchors, not freeform rules.",
    "",
    `TASK: ${JSON.stringify(ctx.taskText)}`,
    `LOCATION: floor=${ctx.floorLabel} zoneKind=${ctx.zoneKind}`,
    "ALREADY IN THIS ZONE:",
    local,
    "",
    "LAYER \u2208 {structure, services, finishes}",
    "NATURE \u2208 {IMPOSSIBLE, DESTRUCTIVE, STRONG_PREF, WEAK_PREF, INDIFFERENT} (only IMPOSSIBLE truly forbids)",
    "REASON \u2208 {structural, concealment, curing_time, logistics, quality, policy}",
    "SCOPE.kind \u2208 {same_zone, same_floor, cross_floor(+delta), building_wide, external}",
    "ZONE_KIND \u2208 {dry, wet, balcony, common, external, shaft}",
    "",
    "TASK-TYPE VOCABULARY (anchor only to these ids):",
    vocab,
    "",
    'FREEDOM SETS (freedomSet must be one of these ids, null, or "NEW_FREE"):',
    sets,
    "",
    "Provide: layer, trade, appliesTo[], placement[{pred,nature,reason,scope}], conceals[],",
    "concealedBy[], hosts[], hostedBy[], freedomSet, confidence(0..1), rationale."
  ].join("\n");
}
function slugifyTaskId(text) {
  const slug = text.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 48);
  return `user_${slug || "task"}`;
}
function gatewayAnchor(layer) {
  if (layer === "structure")
    return { pred: "slab", nature: SAFE_NATURE, reason: "structural", scope: { kind: "same_floor" }, note: "loose: after the floor structure (needs review)" };
  return { pred: "blockwork", nature: SAFE_NATURE, reason: "logistics", scope: { kind: "same_zone" }, note: "loose: after blockwork gateway (needs review)" };
}
function validateClassification(raw, ctx, lib = LIBRARY, confidenceThreshold = 0.55) {
  const ids = lib.taskTypes;
  const dropped = [];
  let needsReview = false;
  let demoted = false;
  const confidence = clamp01(typeof raw.confidence === "number" ? raw.confidence : 0);
  const lowConfidence = confidence < confidenceThreshold;
  const layer = LAYERS.has(raw.layer) ? raw.layer : "services";
  if (!LAYERS.has(raw.layer)) needsReview = true;
  const appliesTo = (raw.appliesTo ?? []).filter((z) => ZONE_KINDS.has(z));
  if (appliesTo.length === 0) appliesTo.push(ctx.zoneKind);
  const cleanRefs = (xs) => (xs ?? []).filter((x) => ids.has(x));
  const conceals = cleanRefs(raw.conceals);
  const concealedBy = cleanRefs(raw.concealedBy);
  const hosts = cleanRefs(raw.hosts);
  const hostedBy = cleanRefs(raw.hostedBy);
  const seq = [];
  for (const p of raw.placement ?? []) {
    if (p.pred === "UNKNOWN") {
      needsReview = true;
      dropped.push({ pred: "UNKNOWN", why: "LLM could not anchor" });
      continue;
    }
    if (!ids.has(p.pred)) {
      dropped.push({ pred: p.pred, why: "not a known TaskTypeId" });
      continue;
    }
    let nature = NATURES.has(p.nature) ? p.nature : SAFE_NATURE;
    if (!NATURES.has(p.nature)) needsReview = true;
    const reason = REASONS.has(p.reason) ? p.reason : SAFE_REASON;
    const scope = sanitizeScope(p.scope);
    if (lowConfidence && (nature === "IMPOSSIBLE" || nature === "DESTRUCTIVE")) {
      nature = SAFE_NATURE;
      demoted = true;
    }
    seq.push({ pred: p.pred, nature, reason, scope, note: `classified: ${truncate(raw.rationale, 80)}` });
  }
  const id = slugifyTaskId(ctx.taskText);
  const freedomSet = resolveFreedomSet(raw.freedomSet, lib);
  let candidate = {
    id,
    label: ctx.taskText.trim(),
    trade: String(raw.trade || "other").slice(0, 40),
    layer,
    instancing: "per_zone",
    appliesTo: dedupe(appliesTo),
    seq,
    conceals,
    concealedBy,
    hosts,
    hostedBy,
    freedomSet: freedomSet ?? void 0
  };
  let looselyAttached = false;
  if (introducesCycle(lib, candidate)) {
    dropped.push(...candidate.seq.map((e) => ({ pred: e.pred, why: "rejected: would create a cycle" })));
    candidate = { ...candidate, seq: [], hosts: [] };
    needsReview = true;
  }
  if (candidate.seq.length === 0 || lowConfidence) {
    if (candidate.seq.length === 0) {
      candidate = { ...candidate, seq: [gatewayAnchor(candidate.layer)] };
      looselyAttached = true;
    }
    needsReview = true;
  }
  return { taskType: candidate, needsReview, confidence, rationale: String(raw.rationale ?? ""), demoted, droppedEdges: dropped, looselyAttached };
}
async function classifyUserTask(ctx, llm, opts = {}) {
  const lib = opts.lib ?? LIBRARY;
  const prompt = buildClassifierPrompt(ctx, lib);
  const raw = await llm(prompt, ctx);
  return validateClassification(raw, ctx, lib, opts.confidenceThreshold ?? 0.55);
}
function clamp01(n) {
  return n < 0 ? 0 : n > 1 ? 1 : n;
}
function dedupe(xs) {
  return [...new Set(xs)];
}
function truncate(s, n) {
  return (s ?? "").length > n ? s.slice(0, n) + "\u2026" : s ?? "";
}
function sanitizeScope(s) {
  if (!s || typeof s !== "object" || !SCOPE_KINDS.has(s.kind)) return SAFE_SCOPE;
  const k = s.kind;
  if (k === "cross_floor") {
    const delta = Number(s.delta);
    return { kind: "cross_floor", delta: Number.isFinite(delta) ? delta : 0 };
  }
  return { kind: k };
}
function resolveFreedomSet(v, lib) {
  if (!v || v === "NEW_FREE") return null;
  return lib.freedomSets.has(v) ? v : null;
}
function introducesCycle(lib, candidate) {
  const adj = /* @__PURE__ */ new Map();
  const push = (from, to) => {
    if (!adj.has(from)) adj.set(from, []);
    adj.get(from).push(to);
  };
  for (const t of lib.taskTypes.values())
    for (const e of t.seq) {
      const crossFloor = e.scope.kind === "cross_floor" && e.scope.delta !== 0;
      if (isHardNature(e.nature, e.reason) && !crossFloor) push(e.pred, t.id);
    }
  for (const e of candidate.seq) {
    const crossFloor = e.scope.kind === "cross_floor" && e.scope.delta !== 0;
    if (isHardNature(e.nature, e.reason) && !crossFloor) push(e.pred, candidate.id);
  }
  for (const h of candidate.hosts ?? []) push(candidate.id, h);
  const WHITE = 0, GRAY = 1, BLACK = 2;
  const color = /* @__PURE__ */ new Map();
  const allNodes = /* @__PURE__ */ new Set([...lib.taskTypes.keys(), candidate.id]);
  let cyclic = false;
  const visit = (n) => {
    if (cyclic) return;
    color.set(n, GRAY);
    for (const m of adj.get(n) ?? []) {
      const c = color.get(m) ?? WHITE;
      if (c === GRAY) {
        cyclic = true;
        return;
      }
      if (c === WHITE) visit(m);
    }
    color.set(n, BLACK);
  };
  for (const n of allNodes) if ((color.get(n) ?? WHITE) === WHITE) visit(n);
  return cyclic;
}

// src/lib/siteOps/engine/persist.ts
function toPersistRows(graph, project) {
  const { preds } = buildAdjacency(graph);
  const rows = [];
  for (const n of graph.nodes.values()) {
    const binding = (preds.get(n.id) ?? []).filter((e) => isHardNature(e.nature, e.reason)).map((e) => ({
      node_key: e.from,
      task_type_id: graph.nodes.get(e.from).taskTypeId,
      nature: e.nature,
      reason: e.reason
    }));
    rows.push({
      project_id: project.project_id,
      org_id: project.org_id,
      node_key: n.id,
      task_type_id: n.taskTypeId,
      phase: n.layer,
      // layer doubles as the coarse phase grouping
      trade: n.trade,
      floor_label: n.floorLabel,
      unit_label: n.unitLabel,
      zone_id: n.zoneId,
      name: n.label,
      seq_no: n.seqNo,
      source: n.source,
      // 'generated' for authored, 'manual' for classified user tasks
      placement_source: n.placementSource,
      order_source: "auto",
      needs_review: !!n.needsReview,
      binding
    });
  }
  return rows.sort((a, b) => a.seq_no - b.seq_no);
}
function reconcile(existing, fresh) {
  const existingByKey = /* @__PURE__ */ new Map();
  for (const r of existing) if (r.node_key) existingByKey.set(r.node_key, r);
  const freshByKey = /* @__PURE__ */ new Map();
  for (const r of fresh) freshByKey.set(r.node_key, r);
  const toInsert = [];
  const toUpdateSeq = [];
  let keptManualOrder = 0;
  for (const row of fresh) {
    const prior = existingByKey.get(row.node_key);
    if (!prior) {
      toInsert.push(row);
      continue;
    }
    if (prior.order_source === "manual") {
      keptManualOrder++;
      continue;
    }
    if (prior.seq_no !== row.seq_no) toUpdateSeq.push({ task_id: prior.task_id, seq_no: row.seq_no });
  }
  const toDeleteIds = [];
  let keptManual = 0;
  for (const row of existing) {
    if (row.source === "manual") {
      keptManual++;
      continue;
    }
    if (!row.node_key) {
      keptManual++;
      continue;
    }
    if (freshByKey.has(row.node_key)) continue;
    if (row.order_source === "manual") {
      keptManualOrder++;
      continue;
    }
    toDeleteIds.push(row.task_id);
  }
  return { toInsert, toUpdateSeq, toDeleteIds, keptManual, keptManualOrder };
}
async function persistGraph(supabase, project, graph) {
  const fresh = toPersistRows(graph, project);
  const { data: existing, error: eErr } = await supabase.from("site_tasks").select("task_id, node_key, source, order_source, seq_no").eq("project_id", project.project_id);
  if (eErr) throw new Error(`load existing tasks: ${eErr.message}`);
  const plan = reconcile(existing ?? [], fresh);
  if (plan.toDeleteIds.length) {
    const { error } = await supabase.from("site_tasks").delete().in("task_id", plan.toDeleteIds);
    if (error) throw new Error(`delete obsolete authored rows: ${error.message}`);
  }
  if (plan.toInsert.length) {
    const { error } = await supabase.from("site_tasks").insert(plan.toInsert);
    if (error) throw new Error(`insert tasks: ${error.message}`);
  }
  for (const u of plan.toUpdateSeq) {
    const { error } = await supabase.from("site_tasks").update({ seq_no: u.seq_no }).eq("task_id", u.task_id);
    if (error) throw new Error(`update seq_no for ${u.task_id}: ${error.message}`);
  }
  return {
    inserted: plan.toInsert.length,
    updated: plan.toUpdateSeq.length,
    deleted: plan.toDeleteIds.length,
    keptManual: plan.keptManual,
    keptManualOrder: plan.keptManualOrder
  };
}

// src/lib/siteOps/engine/viewModel.ts
var NATURE_RANK2 = {
  IMPOSSIBLE: 4,
  DESTRUCTIVE: 3,
  STRONG_PREF: 2,
  WEAK_PREF: 1,
  INDIFFERENT: 0
};
function buildProjectVM(projectId, constructionStack, completionState = /* @__PURE__ */ new Map(), opts = {}) {
  const lib = opts.lib ?? LIBRARY;
  const geometry = stackToGeometry(constructionStack, {
    hasLift: opts.hasLift,
    hasCommonAreas: opts.hasCommonAreas,
    hasExternalWorks: opts.hasExternalWorks,
    commonSystems: opts.commonSystems,
    suppressedTasks: opts.suppressedTasks
  });
  const graph = instantiate(geometry, lib);
  const concreteState = /* @__PURE__ */ new Map();
  for (const n of graph.nodes.values()) {
    const s = completionState.get(n.id) ?? completionState.get(foldKeyOf(n));
    if (s) concreteState.set(n.id, s);
  }
  const ev = new Evaluator(graph, concreteState, lib);
  const { preds, succs } = buildAdjacency(graph);
  const canon = canonicalRank(lib);
  const floors = geometry.floors.slice().sort((a, b) => a.index - b.index).map((floor) => buildFloorVM(floor, graph, ev, preds, succs, lib, canon));
  const foundationFloor = buildFoundationFloorVM(graph, ev, preds, succs, lib, canon);
  if (foundationFloor) floors.unshift(foundationFloor);
  const commonFloor = buildCommonFloorVM(graph, ev, preds, succs, lib, canon);
  if (commonFloor) floors.push(commonFloor);
  let pDone = 0, pTotal = 0;
  for (const f of floors) {
    pDone += f._counts?.done ?? 0;
    pTotal += f._counts?.total ?? 0;
  }
  const overallPct = pTotal ? Math.round(pDone / pTotal * 100) : 0;
  for (const f of floors) delete f._counts;
  return {
    projectId,
    name: opts.name ?? projectId,
    floors,
    overallPct,
    generatedAt: opts.generatedAt ?? (/* @__PURE__ */ new Date()).toISOString(),
    dryRun: opts.dryRun ?? false
  };
}
function foldKeyOf(n) {
  if (n.zoneId === null) return n.floorLabel ? `${n.taskTypeId}@${n.floorLabel}` : n.taskTypeId;
  const unitKey = n.unitLabel ? n.unitLabel.replace(/\s+/g, "") : "unit";
  return `${n.taskTypeId}@${n.floorLabel}/${unitKey}`;
}
var FOUNDATION_TYPES = /* @__PURE__ */ new Set([
  "ground_clearance",
  "excavation",
  "pcc_bed",
  "footing",
  "footing_column",
  "backfill",
  "plinth_beam",
  "plinth_fill",
  "foundation"
]);
function buildFoundationFloorVM(graph, ev, preds, succs, lib, canon) {
  const fNodes = [...graph.nodes.values()].filter((n) => n.floorIndex === null && n.zoneId === null && FOUNDATION_TYPES.has(n.taskTypeId));
  if (!fNodes.length) return null;
  const synthFloor = { label: "Foundation", index: -1, zones: [] };
  const byType = /* @__PURE__ */ new Map();
  for (const n of fNodes) {
    if (!byType.has(n.taskTypeId)) byType.set(n.taskTypeId, []);
    byType.get(n.taskTypeId).push(n);
  }
  const rank = (tt) => canon.get(tt) ?? 9999;
  const tasks = [...byType.entries()].map(([tt, inst]) => foldTask(tt, inst, "unit", synthFloor, ev, preds, succs, lib)).sort((a, b) => rank(a.taskType) - rank(b.taskType) || a.seqNo - b.seqNo);
  const done = tasks.filter((t) => t.status === "done").length;
  const total = tasks.length;
  const pc = total ? Math.round(done / total * 100) : 0;
  const fills = pc === 100 && total > 0 ? [["done", 100]] : pc > 0 ? [["struct", pc]] : [];
  const block = {
    zoneId: "Foundation/unit",
    name: "Substructure",
    kind: "common",
    tasks,
    layerPct: { structure: pc, services: 0, finishes: 0 },
    overallPct: pc,
    stage: pc === 100 ? { label: "Complete", key: "done" } : { label: "Substructure", key: "structure" }
  };
  return { id: "F0", name: "Foundation", index: -1, pc, fills, blocks: [block], _counts: { done, total } };
}
function buildCommonFloorVM(graph, ev, preds, succs, lib, canon) {
  const cNodes = [...graph.nodes.values()].filter((n) => n.floorIndex === null && n.zoneId === null && n.taskTypeId.startsWith("ca_"));
  if (!cNodes.length) return null;
  const synthFloor = { label: "Common areas", index: 9999, zones: [] };
  const byType = /* @__PURE__ */ new Map();
  for (const n of cNodes) {
    if (!byType.has(n.taskTypeId)) byType.set(n.taskTypeId, []);
    byType.get(n.taskTypeId).push(n);
  }
  const rank = (tt) => canon.get(tt) ?? 9999;
  const tasks = [...byType.entries()].map(([tt, inst]) => foldTask(tt, inst, "unit", synthFloor, ev, preds, succs, lib)).sort((a, b) => rank(a.taskType) - rank(b.taskType) || a.seqNo - b.seqNo);
  const done = tasks.filter((t) => t.status === "done").length;
  const total = tasks.length;
  const pc = total ? Math.round(done / total * 100) : 0;
  const fills = pc === 100 && total > 0 ? [["done", 100]] : pc > 0 ? [["struct", pc]] : [];
  const block = {
    zoneId: "Common/unit",
    name: "Amenities",
    kind: "common",
    tasks,
    layerPct: {
      structure: pctDone(tasks.filter((t) => t.layer === "structure")),
      services: pctDone(tasks.filter((t) => t.layer === "services")),
      finishes: pctDone(tasks.filter((t) => t.layer === "finishes"))
    },
    overallPct: pc,
    stage: pc === 100 ? { label: "Complete", key: "done" } : { label: "Common areas", key: "structure" }
  };
  return { id: "CA", name: "Common areas", index: 9999, pc, fills, blocks: [block], _counts: { done, total } };
}
function buildFloorVM(floor, graph, ev, preds, succs, lib, canon) {
  const floorNodes = [...graph.nodes.values()].filter((n) => n.floorIndex === floor.index);
  const perFloorStructural = floorNodes.filter((n) => n.zoneId === null);
  const zoneNodes = floorNodes.filter((n) => n.zoneId !== null);
  const unitKeys = [...new Set(zoneNodes.map((n) => n.unitLabel ?? "\u2205"))];
  const blocks = (unitKeys.length ? unitKeys : ["\u2205"]).map((uk) => {
    const unitZoneNodes = zoneNodes.filter((n) => (n.unitLabel ?? "\u2205") === uk);
    const unitLabel = uk === "\u2205" ? null : uk;
    return buildBlockVM(floor, unitLabel, perFloorStructural, unitZoneNodes, ev, preds, succs, lib, canon);
  });
  const distinct = [];
  if (blocks.length) {
    const structural = blocks[0].tasks.filter((t) => t.layer === "structure");
    distinct.push(...structural);
    for (const b of blocks) distinct.push(...b.tasks.filter((t) => t.layer !== "structure"));
  }
  const done = distinct.filter((t) => t.status === "done").length;
  const total = distinct.length;
  const pc = total ? Math.round(done / total * 100) : 0;
  let fills;
  if (pc === 100 && total > 0) fills = [["done", 100]];
  else {
    fills = [["structure", "struct"], ["services", "serv"], ["finishes", "fin"]].map(([layer, tag]) => {
      const doneInLayer = distinct.filter((t) => t.layer === layer && t.status === "done").length;
      return [tag, total ? Math.round(doneInLayer / total * 100) : 0];
    }).filter(([, v]) => v > 0);
  }
  return {
    id: floorId(floor.label),
    name: floor.label,
    index: floor.index,
    pc,
    fills,
    blocks,
    _counts: { done, total }
  };
}
function buildBlockVM(floor, unitLabel, perFloorStructural, unitZoneNodes, ev, preds, succs, lib, canon) {
  const unitKey = unitLabel ? unitLabel.replace(/\s+/g, "") : "unit";
  const byType = /* @__PURE__ */ new Map();
  for (const n of [...perFloorStructural, ...unitZoneNodes]) {
    if (!byType.has(n.taskTypeId)) byType.set(n.taskTypeId, []);
    byType.get(n.taskTypeId).push(n);
  }
  const rank = (tt) => canon.get(tt) ?? 9999;
  const tasks = [...byType.entries()].map(
    ([taskType2, instances]) => foldTask(taskType2, instances, unitKey, floor, ev, preds, succs, lib)
  ).sort((a, b) => rank(a.taskType) - rank(b.taskType) || a.seqNo - b.seqNo);
  const layerPct = {
    structure: pctDone(tasks.filter((t) => t.layer === "structure")),
    services: pctDone(tasks.filter((t) => t.layer === "services")),
    finishes: pctDone(tasks.filter((t) => t.layer === "finishes"))
  };
  const overallPct = pctDone(tasks);
  const repZone = unitZoneNodes[0]?.zoneKind ?? "dry";
  return {
    zoneId: `${floor.label}/${unitKey}`,
    name: unitLabel ?? "Whole floor",
    kind: repZone,
    tasks,
    layerPct,
    overallPct,
    stage: deriveStage(layerPct)
  };
}
function foldTask(taskType2, instances, unitKey, floor, ev, preds, succs, lib) {
  const tt = lib.taskTypes.get(taskType2);
  const isBuilding = instances[0].floorLabel === null;
  const isPerFloor = instances[0].zoneId === null;
  const nodeKey = isBuilding ? taskType2 : isPerFloor ? `${taskType2}@${floor.label}` : `${taskType2}@${floor.label}/${unitKey}`;
  const statuses = instances.map((n) => ev.availability(n.id));
  const status = statuses.every((s) => s === "done") ? "done" : statuses.some((s) => s === "active") ? "active" : statuses.some((s) => s === "available") ? "available" : "blocked";
  const seqNo = Math.min(...instances.map((n) => n.seqNo));
  let why;
  if (status === "blocked") {
    const blockedInst = instances.find((n) => ev.availability(n.id) === "blocked");
    const seen = /* @__PURE__ */ new Set();
    why = ev.why(blockedInst.id).map((b) => ({
      afterLabel: lib.taskTypes.get(b.taskTypeId)?.label ?? b.taskTypeId,
      reason: b.reason
    })).filter((w) => seen.has(w.afterLabel) ? false : (seen.add(w.afterLabel), true));
  }
  const hardPreds = foldEdges(instances.flatMap((n) => preds.get(n.id) ?? []), "from", ev, lib);
  const hardDeps = foldEdges(instances.flatMap((n) => succs.get(n.id) ?? []), "to", ev, lib);
  return {
    nodeKey,
    taskType: taskType2,
    label: tt?.label ?? taskType2,
    trade: tt?.trade ?? instances[0].trade,
    layer: instances[0].layer,
    status,
    seqNo,
    why,
    freedomSet: tt?.freedomSet,
    placementSource: instances[0].placementSource,
    needsReview: instances.some((n) => n.needsReview) || void 0,
    hardPreds,
    hardDeps
  };
}
function foldEdges(edges, side, ev, lib) {
  const byType = /* @__PURE__ */ new Map();
  for (const e of edges) {
    if (!isHardNature(e.nature, e.reason)) continue;
    const otherId = side === "from" ? e.from : e.to;
    const node = ev.graph.nodes.get(otherId);
    if (!node) continue;
    const existing = byType.get(node.taskTypeId);
    if (!existing || NATURE_RANK2[e.nature] > NATURE_RANK2[existing.nature]) {
      byType.set(node.taskTypeId, {
        nodeKey: otherId,
        taskType: node.taskTypeId,
        label: lib.taskTypes.get(node.taskTypeId)?.label ?? node.taskTypeId,
        nature: e.nature,
        reason: e.reason
      });
    }
  }
  return [...byType.values()];
}
function pctDone(tasks) {
  if (!tasks.length) return 0;
  return Math.round(tasks.filter((t) => t.status === "done").length / tasks.length * 100);
}
function deriveStage(layerPct) {
  if (layerPct.finishes > 0) return layerPct.finishes === 100 ? { label: "Complete", key: "done" } : { label: "Finishing", key: "finishes" };
  if (layerPct.services > 0) return { label: "Services", key: "services" };
  if (layerPct.structure === 100) return { label: "Structure done", key: "structure" };
  return { label: "Structuring", key: "structure" };
}
function floorId(label) {
  const map = { Ground: "G", First: "1", Second: "2", Third: "3", Fourth: "4", Fifth: "5", Terrace: "T", Stilt: "S", Cellar: "C" };
  return map[label] ?? label.charAt(0).toUpperCase();
}
export {
  CycleError,
  Evaluator,
  LIBRARY,
  buildAdjacency,
  buildClassifierPrompt,
  buildLibrary,
  buildProjectVM,
  classifyUserTask,
  emptyState,
  evaluate,
  instantiate,
  isHardNature,
  persistGraph,
  reconcile,
  slugifyTaskId,
  stackToGeometry,
  stateOf,
  taskType,
  toPersistRows,
  validateClassification,
  validateLibrary
};
