// Shared construction-config capture — THE single source used by all four mount points
// (NewProjectWizard, OnboardingWizard, ProjectDetail "set up tasks", and indirectly the task
// view). Presentation + the branched submit logic only; each wrapper supplies its own chrome
// and decides what happens onComplete.
//
// Supported types (Residential/Villa/Apartment) → write the resolved stack + generate the task
// set FROM THE ENGINE (constraint library → geometry → graph → persistGraph). The legacy expander
// is retired here (2026-07-11): it wrote a second, overlapping task vocabulary that made every
// downstream question ambiguous. Unsupported types (Commercial/Industrial/Renovation) → save the
// type, skip generation, return a graceful signal — block 0's scope limit degrading cleanly.

import { useState } from 'react'
import { supabase } from '../../lib/supabase'
import { buildStack } from '../../lib/siteOps/expander'
import { instantiate, stackToGeometry, persistGraph } from '../../lib/siteOps/engine'

const SUPPORTED = ['Residential', 'Villa', 'Apartment']

export interface ConfigResult {
  generated: boolean
  taskCount?: number
  reason?: 'unsupported_type'
}

interface Props {
  projectId: string
  projectType: string
  onComplete: (result: ConfigResult) => void
  onSkip?: () => void
}

const PARKING: { value: 'none' | 'stilt' | 'cellar'; label: string; hint: string }[] = [
  { value: 'none', label: 'None', hint: 'Porch / open' },
  { value: 'stilt', label: 'Stilt', hint: 'Parking level at grade' },
  { value: 'cellar', label: 'Cellar', hint: 'Parking below ground' },
]

// Opt-in common-area / amenity systems — ids MUST match the engine's ca_* task-types (library.ts).
// Ticking one surfaces it in the project's "Common areas" stage.
const CA_SYSTEMS: { id: string; label: string }[] = [
  { id: 'ca_lift', label: 'Lift' },
  { id: 'ca_parking', label: 'Parking' },
  { id: 'ca_stair', label: 'Common staircase' },
  { id: 'ca_corridor', label: 'Corridor finishes' },
  { id: 'ca_fire', label: 'Fire fighting' },
  { id: 'ca_oht', label: 'Overhead tank' },
  { id: 'ca_ugt', label: 'Sump / UG tank' },
  { id: 'ca_borewell', label: 'Borewell' },
  { id: 'ca_stp', label: 'STP' },
  { id: 'ca_transformer', label: 'Transformer' },
  { id: 'ca_generator', label: 'DG / generator' },
  { id: 'ca_solar', label: 'Rooftop solar' },
  { id: 'ca_compound', label: 'Compound wall & gate' },
  { id: 'ca_landscaping', label: 'Landscaping' },
]

export default function ConstructionConfig({ projectId, projectType, onComplete, onSkip }: Props) {
  const supported = SUPPORTED.includes(projectType)

  const [parking, setParking] = useState<'none' | 'stilt' | 'cellar'>('none')
  const [floors, setFloors] = useState(1)
  const [units, setUnits] = useState(1)
  const [commonSet, setCommonSet] = useState<Set<string>>(new Set())
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')

  async function submit() {
    setBusy(true)
    setError('')
    try {
      if (!supported) {
        // graceful degrade — persist the type, no generation
        const { error: e } = await supabase.from('projects').update({ project_type: projectType }).eq('project_id', projectId)
        if (e) throw e
        onComplete({ generated: false, reason: 'unsupported_type' })
        return
      }
      const hasCommon = commonSet.size > 0
      const stack = buildStack({ dedicated_parking: parking, habitable_floors: floors, units_per_floor: units, has_common_areas: hasCommon })
      const baseUpdate = {
        construction_stack: stack,
        dedicated_parking: parking,
        habitable_floors: floors,
        units_per_floor: units,
        has_common_areas: hasCommon,
        project_type: projectType,
        sequence_model: 'rcc_residential',
      }
      // common_systems is a later migration; persist it when present, else fall back gracefully.
      let e = (await supabase.from('projects').update({ ...baseUpdate, common_systems: [...commonSet] }).eq('project_id', projectId)).error
      if (e) e = (await supabase.from('projects').update(baseUpdate).eq('project_id', projectId)).error
      if (e) throw e

      // ── GENERATED BY THE ENGINE (2026-07-11) ────────────────────────────────────────────────────
      // This used to call the legacy expander (generateSiteTasks + docs/site-ops/sequence.json), which
      // wrote a SECOND task vocabulary on top of the engine's — the same building described twice
      // ("False Ceiling" ≡ "Ceiling — false-ceiling frame", "Tiling" ≡ "Floor tiling" + "Wall tiling").
      // Every project created here seeded the duplication the resolver then had to ask questions about.
      // ONE generator now: the constraint library → geometry → graph → persistGraph. Same door the
      // Sequence view and the WhatsApp materializer use, so a row is the same row whoever made it —
      // node_key, task_type_id, binding and all.
      const { data: proj } = await supabase.from('projects').select('org_id').eq('project_id', projectId).maybeSingle()
      if (!proj?.org_id) throw new Error('project has no org')
      const geometry = stackToGeometry(stack, {
        hasCommonAreas: hasCommon, hasExternalWorks: hasCommon, commonSystems: [...commonSet],
      })
      const res = await persistGraph(supabase, { project_id: projectId, org_id: proj.org_id }, instantiate(geometry))
      onComplete({ generated: true, taskCount: res.inserted })
    } catch (err) {
      setError((err as Error)?.message ?? 'Could not set up tasks. Please try again.')
      setBusy(false)
    }
  }

  // ── unsupported type: no questions, a clean note + continue ──
  if (!supported) {
    return (
      <div className="flex flex-col gap-4">
        <div>
          <h3 className="font-data-mono text-[11px] font-semibold uppercase tracking-wide text-on-surface-variant/60">Task plan</h3>
          <p className="mt-1 text-[15px] text-on-surface">Automatic task planning isn't available for <span className="font-semibold">{projectType}</span> projects yet.</p>
          <p className="mt-1 text-[13px] text-on-surface-variant/70">Your project is saved — you can add tasks manually later. We're building the {projectType.toLowerCase()} sequence from real jobs first.</p>
        </div>
        {error && <p className="text-[13px] text-error">{error}</p>}
        <div className="flex gap-2">
          {onSkip && <button onClick={onSkip} disabled={busy} className="flex-1 rounded-xl border border-outline-variant/40 py-2.5 text-[14px] font-medium text-on-surface-variant">Skip</button>}
          <button onClick={submit} disabled={busy} className="flex-1 rounded-xl py-2.5 text-[14px] font-semibold text-white" style={{ background: '#C8603A' }}>{busy ? 'Saving…' : 'Got it'}</button>
        </div>
      </div>
    )
  }

  // ── supported: the three questions ──
  return (
    <div className="flex flex-col gap-5">
      <div>
        <h3 className="font-data-mono text-[11px] font-semibold uppercase tracking-wide text-on-surface-variant/60">Set up the task plan</h3>
        <p className="mt-1 text-[14px] text-on-surface-variant/80">Three quick questions build the site task skeleton.</p>
      </div>

      {/* parking */}
      <div>
        <label className="mb-1.5 block text-[13px] font-medium text-on-surface">Dedicated parking level?</label>
        <div className="grid grid-cols-3 gap-2">
          {PARKING.map((p) => {
            const on = parking === p.value
            return (
              <button key={p.value} onClick={() => setParking(p.value)}
                className={`rounded-xl border px-2 py-2.5 text-left transition ${on ? 'border-transparent text-white' : 'border-outline-variant/40 text-on-surface'}`}
                style={on ? { background: '#C8603A' } : undefined}>
                <div className="text-[14px] font-semibold">{p.label}</div>
                <div className={`text-[11px] ${on ? 'text-white/80' : 'text-on-surface-variant/60'}`}>{p.hint}</div>
              </button>
            )
          })}
        </div>
      </div>

      {/* floors + units */}
      <div className="grid grid-cols-2 gap-3">
        <Stepper label="Habitable floors" hint="Ground + uppers" value={floors} setValue={setFloors} min={1} />
        <Stepper label="Units per floor" hint="1 = single home" value={units} setValue={setUnits} min={1} />
      </div>

      {/* common areas / amenities — tick what this project has */}
      <div>
        <label className="mb-1.5 block text-[13px] font-medium text-on-surface">Common areas & amenities</label>
        <p className="mb-2 text-[11px] text-on-surface-variant/60">Tick what applies — each becomes a task in the project's Common areas stage.</p>
        <div className="flex flex-wrap gap-2">
          {CA_SYSTEMS.map((s) => {
            const on = commonSet.has(s.id)
            return (
              <button key={s.id} type="button"
                onClick={() => setCommonSet((prev) => { const n = new Set(prev); n.has(s.id) ? n.delete(s.id) : n.add(s.id); return n })}
                className={`rounded-full border px-3 py-1.5 text-[12.5px] font-medium transition ${on ? 'border-transparent text-white' : 'border-outline-variant/40 text-on-surface-variant'}`}
                style={on ? { background: '#C8603A' } : undefined}>
                {on ? '✓ ' : ''}{s.label}
              </button>
            )
          })}
        </div>
      </div>

      {error && <p className="text-[13px] text-error">{error}</p>}

      <div className="flex gap-2">
        {onSkip && <button onClick={onSkip} disabled={busy} className="rounded-xl border border-outline-variant/40 px-4 py-2.5 text-[14px] font-medium text-on-surface-variant">Skip for now</button>}
        <button onClick={submit} disabled={busy} className="flex-1 rounded-xl py-2.5 text-[14px] font-semibold text-white" style={{ background: '#C8603A' }}>
          {busy ? 'Generating…' : 'Generate task plan'}
        </button>
      </div>
    </div>
  )
}

function Stepper({ label, hint, value, setValue, min }: { label: string; hint: string; value: number; setValue: (n: number) => void; min: number }) {
  return (
    <div>
      <label className="mb-1.5 block text-[13px] font-medium text-on-surface">{label}</label>
      <div className="flex items-center rounded-xl border border-outline-variant/40">
        <button onClick={() => setValue(Math.max(min, value - 1))} className="px-3.5 py-2 text-[18px] text-on-surface-variant">−</button>
        <input type="number" value={value} min={min}
          onChange={(e) => setValue(Math.max(min, parseInt(e.target.value || String(min), 10) || min))}
          className="w-full border-x border-outline-variant/40 bg-transparent py-2 text-center font-data-mono text-[15px] font-semibold text-on-surface outline-none" />
        <button onClick={() => setValue(value + 1)} className="px-3.5 py-2 text-[18px] text-on-surface-variant">+</button>
      </div>
      <p className="mt-1 text-[11px] text-on-surface-variant/55">{hint}</p>
    </div>
  )
}
