// WE OFFERED HIM A ROW THAT NO LONGER EXISTED (live probe, 2026-07-13, 17:19).
//
// A photo of The Pride's first-floor false ceilings. The site has one floor (Ground), so we correctly said
// so and asked which of the real rows he meant. He tapped the one option we gave him:
//
//     1. Ceiling — false-ceiling frame — Ground
//
// …and we answered "Couldn't update it just now — saved it for review." The row he picked was gone. The
// logs of that second turn say it plainly, in this order:
//
//     [siteops:materialize] existingRows=87 vmNodeKeys=57 inserted=31 retired=61
//     [siteops:GUARDRAIL] REFUSED write to non-VM-visible row node_key=ceiling_frame@Ground#Ground-unit-dry
//
// THE SAME TURN THAT TRIED TO WRITE THE ROW HAD JUST DELETED IT. The project's 87 rows were generated by the
// OLD library — the pre-collapse one, where a floor was cut into zones (`#Ground-unit-dry`). The current
// engine builds 57 zone-free nodes. Nothing had reconciled the gap, because reconcile (persistGraph) is
// only ever reached from a WRITE path — and this project had not been written to since the library changed.
// So the ask turn read 87 stale rows straight out of site_tasks, offered one, and the answer turn healed the
// project mid-pick and shot the row out from under him. The self-heal and the bug are the same line of code.
//
// THE RULE: reconcile before we READ the work, not only before we write it. What we OFFER must be what
// EXISTS. A library change must be absorbed by the first message about the project, not by the unlucky
// message that happens to be a write.
//
// (The fake's selects always return the seed — an insert does not feed back into a later read — so this
// cannot assert "and then the fresh row was offered". What it CAN assert, exactly, is the ORDER: the
// project was reconciled BEFORE we asked the model which task the message was about. That ordering IS the
// fix; the offer's own guard is the VM filter, tested separately.)

import { suite, test, expect } from './harness'
import { fakeSupabase, type Seed } from './fake_supabase'
import { runSiteops } from '../_agents/siteops.ts'

const ORG = 'org-1'
const SENDER = '919900000000'
const CAPTION = 'The pride - 1st floor false ceilings ..unit a'
const DESCRIPTION = 'Installation of false ceilings on the first floor, Unit A.'

// The Pride as the DB held it: one real floor, and a ceiling row keyed the OLD way — a zone-suffixed
// node_key (`#Ground-unit-dry`) the current engine no longer generates. It is `generated`/`auto`, so
// reconcile's job is to retire it and lay down the current rows in its place.
const seed = (): Seed => ({
  projects: [{
    project_id: 'P1', name: 'The Pride', org_id: ORG, status: 'Active', has_common_areas: false,
    construction_stack: { levels: [{ label: 'Ground', kind: 'residential', zones: [{ use: 'residential', units: 1 }] }] },
  }],
  site_tasks: {
    'stale-fcf': {
      task_id: 'stale-fcf', project_id: 'P1', name: 'False-ceiling frame', status: 'OPEN',
      floor_label: 'Ground', unit_label: null, trade: 'ceiling', phase: 'services',
      node_key: 'ceiling_frame@Ground#Ground-unit-dry',   // the dead key, verbatim from the probe
      source: 'generated', order_source: 'auto', seq_no: 1,
    },
  },
  problems: {}, chase_batches: [],
  wa_registered_numbers: [{ user_id: 'u1', phone_number: SENDER, is_active: true }],
  user_profiles: [{ id: 'u1', name: 'Ramesh' }],
  site_narration_id: 'narr-1',
})
const imgCtx = (fake: ReturnType<typeof fakeSupabase>) => ({
  supabase: fake, from: SENDER, orgId: ORG, wamid: 'w-1', lang: 'en' as const,
  image: { base64: 'x', mime: 'image/jpeg', caption: CAPTION, description: DESCRIPTION, storagePath: 'rough/x.jpg' },
})

const VISION = JSON.stringify({
  project_hint: 'The Pride',
  items: [{ type: 'progress', text: DESCRIPTION, confidence: 'high', task_hint: 'ceiling', structure: null, qc_statements: [] }],
})
const RESOLUTION = JSON.stringify({
  issue_snag_found: { found: false, items: [] },
  update_found: {
    found: true,
    updates: [{
      target_id: 'type:P1:false ceiling frame', target_kind: 'task', action: 'progress',
      confidence: 'med', closure_explicit: false, reason: 'false ceilings going in', alt_target_ids: [],
    }],
    nearest: [],
  },
})

interface Turn { fake: ReturnType<typeof fakeSupabase>; insertsWhenAsked: number; askedTheModel: boolean }
async function runTurn(): Promise<Turn> {
  const fake = fakeSupabase(seed())
  let insertsWhenAsked = -1
  let askedTheModel = false
  const inserts = () => fake.writesTo('site_tasks').filter((w) => w.op === 'insert').length
  const model = (_system: string, user: string): Promise<string> => {
    if (user.startsWith('CANDIDATES:')) {
      // the moment we ask "which of this project's work is he talking about?" — what did the DB look like?
      askedTheModel = true
      if (insertsWhenAsked < 0) insertsWhenAsked = inserts()
      return Promise.resolve(RESOLUTION)
    }
    if (user.includes('Decompose the image')) return Promise.resolve(VISION)
    return Promise.resolve('')
  }
  await runSiteops(imgCtx(fake), `${CAPTION} -- ${DESCRIPTION}`, { callModel: model })
  return { fake, insertsWhenAsked, askedTheModel }
}

suite('siteops — reconcile before we READ the work, not only before we write it', () => {
  test('(R1) the project is reconciled BEFORE the model is asked which task the message is about', async () => {
    const { insertsWhenAsked, askedTheModel } = await runTurn()
    expect(askedTheModel).toBe(true)          // the turn did resolve (otherwise this proves nothing)
    expect(insertsWhenAsked > 0).toBe(true)   // …and the current rows already existed when it did
  })

  test('(R2) a turn that changes NO task status still heals the project — the ask turn is the one that offered the dead row', async () => {
    const { fake } = await runTurn()
    const taskWrites = fake.writesTo('site_tasks')
    // nothing advanced a task's status this turn (it ended in a question) …
    expect(taskWrites.some((w) => w.op === 'update' && w.payload?.status)).toBe(false)
    // … and the project was reconciled anyway: the current rows laid down, the dead key retired.
    expect(taskWrites.some((w) => w.op === 'insert')).toBe(true)
    expect(taskWrites.some((w) => w.op === 'update' && w.payload === null)).toBe(true)   // the delete
  })
})
