-- ===========================================================================
-- OUTBOX DELIVERY ORDER — a turn's messages must arrive in the order we said them.
--
-- THE LIVE FAILURE (2026-07-11, 12:50). One turn enqueued four messages, in this order:
--     1. "✅ Got your message — taking a look now…"          (the agent's receipt ack)
--     2. "Got it — I'll take care of this, then come back…"  (the promise to return to the held question)
--     3. "Noted 👍 — nothing updated…"                        (the agent's reply)
--     4. "Back to my earlier question: …"                     (the held question, re-surfaced AFTER the turn)
-- The supervisor received 1, 4, 2, 3. The re-surfaced question jumped ahead of the reply it was supposed to
-- follow, and the promise to come back arrived after we had already come back. The dispatcher's ordering was
-- correct; the DELIVERY was not.
--
-- TWO CAUSES, BOTH HERE:
--   1. `ORDER BY next_attempt_at` has no tiebreaker. Every message in a turn is enqueued with the same
--      default (now()), so they are all tied and the order among them is whatever the plan happens to give.
--   2. `UPDATE … RETURNING` HAS NO GUARANTEED ROW ORDER IN POSTGRES. The ORDER BY inside the id-subselect
--      decides WHICH rows are claimed, not the order they come back — so even distinct timestamps would not
--      have saved us. The drainer then POSTs them in whatever order it received them.
--
-- THE FIX:
--   · `seq` — a real monotonic FIFO key. created_at cannot serve: two messages enqueued in the same
--     millisecond tie, and the id is a random uuid, so a tie is a coin toss.
--   · claim ORDER BY seq, and materialise through a CTE so the ORDER survives the RETURNING.
--   · HEAD OF LINE, per recipient: never send a message past an older one to the same person that is still
--     in flight (SENDING) or backing off after a failure (PENDING with next_attempt_at in the future).
--     Without this, one transient send failure re-orders the whole turn on the retry.
--   · an advisory lock around the claim, so two overlapping drainer ticks cannot interleave two messages to
--     the same recipient. Claims are sub-millisecond; the contention cost is nil next to a mis-ordered turn.
--
-- Additive + idempotent. The ALTER backfills `seq` for existing rows (the table is small and ephemeral —
-- rows are drained and purged), and the function is re-created afterwards so its SETOF public.outbox return
-- type picks the new column up (same dance as 20260702000004).
--
-- ROLLBACK:
--   (restore the previous body from 20260702000004; the `seq` column can stay — it is additive and unused
--    by the old body.)
-- ===========================================================================

ALTER TABLE public.outbox
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- the claim's working set: ready rows, oldest first, and the head-of-line probe (older + undelivered, same
-- recipient). Partial — SENT/FAILED rows are the bulk of the table and are never scanned by either.
CREATE INDEX IF NOT EXISTS outbox_inflight_seq_idx
  ON public.outbox (target, seq)
  WHERE status IN ('PENDING', 'SENDING');

CREATE OR REPLACE FUNCTION public.outbox_claim(p_limit int DEFAULT 20)
RETURNS SETOF public.outbox
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  -- Serialise claims: two overlapping ticks must not each grab one of a recipient's adjacent messages and
  -- race to POST them. Transaction-scoped — released the moment this returns.
  PERFORM pg_advisory_xact_lock(hashtext('outbox_claim'));

  RETURN QUERY
  WITH claimed AS (
    UPDATE public.outbox o
      SET status = 'SENDING', attempts = o.attempts + 1, updated_at = now()
    WHERE o.id IN (
      SELECT p.id
      FROM public.outbox p
      WHERE p.status = 'PENDING'
        AND p.next_attempt_at <= now()
        -- HEAD OF LINE — an older message to the SAME recipient that is in flight, or waiting out a backoff,
        -- blocks this one. (An older PENDING row that is READY is not a blocker: it is claimed in this same
        -- batch and the final ORDER BY puts it first.)
        AND NOT EXISTS (
          SELECT 1
          FROM public.outbox q
          WHERE q.target = p.target
            AND q.seq < p.seq
            AND (
              q.status = 'SENDING'
              OR (q.status = 'PENDING' AND q.next_attempt_at > now())
            )
        )
      ORDER BY p.seq
      FOR UPDATE SKIP LOCKED
      LIMIT p_limit
    )
    RETURNING o.*
  )
  -- the ORDER the drainer POSTs in. UPDATE … RETURNING is unordered; this is what makes it a queue.
  SELECT * FROM claimed ORDER BY seq;
END $$;
