// Aggregator — import every src/lib suite here, then run.
import './payeeSearch.test'
import './genHeads.test'
import './genExpenseLabel.test'
import './walletHolderName.test'
import './amountWords.test'
import './billUnsure.test'
import './txnEntry.test'
import './billPayMath.test'
import './partyLedger.test'
import './projectSearch.test'
import './importParse.test'
import './importResolve.test'
import './importClassify.test'
import './importSheet.test'
import './importCommit.test'
import './partyRoutes.test'
import { runAll } from './harness'

await runAll()
